language: python
python:
  - "3.9"
before-install:
- "export PYTHONPATH=$PYTHONPATH:$(pwd)"
install:
- pip install -r requirements.txt
- pip install coverage
script:
- coverage run --include='gallow.py' -m pytest test_cases.py
- coverage report -m

